name: usercenter-test cicd测试
on: push # 事件出发条件

permissions: # 权限
  contents: write # 读取仓库内容

jobs: # 任务集
  npm-build: #自定义的npm-build工作
    runs-on: ubuntu-latest # 系统运行环境

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4 # 克隆代码

      - name: # 安装依赖&项目打包
        run: | #合并多行命令
          export NODE_OPTIONS=--openssl-legacy-provider
          npm install
          npm run build
      - name: 查看当前目录内容
        run: ls -la # 列出目录内容，确认 build 目录是否存在

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@4.1.5 # 部署到github pages
        with:
          branch: gh-pages # 部署分支
          folder: build # 打包后的文件目录
          token: ${{ secrets.GITHUB_TOKEN }} # 令牌
